### PR TITLE
Create global constant definitions.

### PR DESCRIPTION
**Pull request by fruffy**

### CODE REVIEW

**Comment by robotrobo** [comment]
The tests fail because we need to update the references for the improved performance. Lets merge this?

**Review by robotrobo — APPROVED** [review]

**Comment by fruffy** [comment]
Yes, I will update this over the week end and merge. Maybe today if I find the time.

**Comment by fruffy** [comment]
Or feel free to update the refs and merge yourself.

**Comment by robotrobo** [comment]
Are we removing all if blocks?

**Comment by fruffy** [comment]
No. Sometimes there might be a bug caused by an if statement. So if we remove them outright we may not be able to reduce as much. If statements are pruned with the same probability as statements, I think that is okay. Originally, we had this specific if statement split, but just iterating over statements should be as effective.

**Comment by fruffy** [comment]
This is really frustrating. There is something strange going on with the global random generator. It does not compile with clang-tidy and the randomness seems to change compare to the VM, which is quite unusual. I do not know how this can happen.

**Comment by fruffy** [comment]
@robotrobo I am not sure how to resolve this. Can you check out this pull request and the reference files? I tried to fix several potential sources of inconsistencies but they did not help.

**Comment by robotrobo** [comment]
Alright, my finals are going on this week, so a bit jam-packed, but I'll take a look right after that.

**Comment by fruffy** [comment]
Yeah no problem, just let me know it goes next week.

**Comment by robotrobo** [comment]
It seems to work fine between runs, but fails between different builds

**Comment by robotrobo** [comment]
@fruffy, I couldn’t identify any other sources of a randomness leak, do you think we should switch to another rng engine?

**Comment by fruffy** [comment]
So, do the tests pass locally for you?

**Comment by fruffy** [comment]
> @fruffy, I couldn’t identify any other sources of a randomness leak, do you think we should switch to another rng engine?

We could try one, if it is not too much effort to instrument or install. The standard random is just very limited, but we do not need much.

**Comment by robotrobo** [comment]
> So, do the tests pass locally for you?

No, they don’t

**Comment by robotrobo** [comment]
> > So, do the tests pass locally for you?
> 
> No, they don’t

They only do so, if I created the refs in this build, and then they start failing again for the next one

**Comment by fruffy** [comment]
Okay then, let's use your refs and see what happens. Can you push them?

**Comment by robotrobo** [comment]
> Okay then, let's use your refs and see what happens. Can you push them?

No but, if I push them, the test will fail regardless it will be a new build, right? So, what i am saying is, in a particular build, even if i run the pruner 10 times, it will always be the same output with the same seed. But, if I recompile pruner, it gives another output with the same seed, failing the tests

**Comment by fruffy** [comment]
Are you sure? That would be very strange. My assumption was that it could be a difference in the boost version or OS. So CI is different from what I have. The randomness should be independent of the build.

**Comment by robotrobo** [comment]
You are correct, it was the way I created my references.

**Comment by fruffy** [comment]
Can you also add the ref files?

**Comment by robotrobo** [comment]
It creates the exact same references for me

**Comment by fruffy** [comment]
Ah that is unfortunate, I was hoping your setup would be similar to CI. Really strange behavior.

**Comment by robotrobo** [comment]
I don't understand how can this be the case with the actions machine, if both of our machines produce the same result.

**Comment by fruffy** [comment]
Finally got this to work. The issue was really silly. The incorrect commit source was checked out and did not update. Now all tests pass. However, there is another problem. The paths to the P4C binaries are incorrect locally. This can easily be fixed by updating https://github.com/p4gauntlet/toz3/pull/10/files#diff-7149cd7f390844c77d970f880c7587263fcfda840584217bf62cb0ce089d269aR39. For now, I will merge this. As a next step, I will switch to cmake tests instead of pytest.

**Pull request merged**
